6.Write a numpy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [6]:
import numpy as np
def checkerBoard(n):
    print("Checkerboard pattern: ")
    arr=np.zeros((8,8),dtype=int)
    arr[1::2,::2]=1
    arr[::2,1::2]=1
    print(arr)
n=8
checkerBoard(n)

Checkerboard pattern: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


7.Write a numpy program to test whether each element of a 1D array is also in a second array.

In [10]:
import numpy as np
arr1=np.array([4,7,0,3,])
print("Array 1: ",arr1)
arr2=np.array([0,1,2])
print("Array 2: ",arr2)
print("Comparing each element of array 1 and 2: ")
print(np.in1d(arr1,arr2))

Array 1:  [4 7 0 3]
Array 2:  [0 1 2]
Comparing each element of array 1 and 2: 
[False False  True False]


8.Create a numpy program to :
a)Create two arrays
b)Find the common elements in the created two arrays
c)Find the union of the created two arrays

In [12]:
import numpy as np
arr1=np.array([0,1,2,3,4,5])
print(arr1)
arr2=np.array([1,2,9])
print(arr2)
print("Common Elements :",np.intersect1d(arr1,arr2))
print("Union of arrays: ",np.union1d(arr1,arr2))

[0 1 2 3 4 5]
[1 2 9]
Common Elements : [1 2]
Union of arrays:  [0 1 2 3 4 5 9]


9.Write a numpy program to get unique elements of an array.

In [13]:
import numpy as np
arr=np.array([0,1,1,25,2,4,6,3,3,8])
print("Unique elements of the array: ",np.unique(arr))

Unique elements of the array:  [ 0  1  2  3  4  6  8 25]


10.Write a program to convert numpy array to python list sructure.

In [18]:
import numpy as np
arr=np.arange(0,6)
print("Array: ",arr)
ls=arr.tolist()
print("List: ",ls)

Array:  [0 1 2 3 4 5]
List:  [0, 1, 2, 3, 4, 5]


In [30]:
import numpy as np
arr=np.zeros((8,8),dtype=int)
arr[0::2,4::1]=1
arr[1::2,0:4:1]=1
print(arr)

[[0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]]


In [31]:
import numpy as np
arr=np.zeros((8,8),dtype=int)
arr[0::2,:2:1]=1
arr[0::2,4:6:1]=1
arr[1::2,2:4:1]=1
arr[1::2,6:8:1]=1
print(arr)

[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]


11.Write a numpy program to access array by column.

In [33]:
import numpy as np
arr=np.arange(0,10)
arr=arr.reshape(5,2)
print(arr)
print("Elements of first column: ",arr[:,0])
print("Elements of Second column: ",arr[:,1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Elements of first column:  [0 2 4 6 8]
Elements of Second column:  [1 3 5 7 9]


In [10]:
import numpy as np
mat1=np.arange(1,5).reshape(2,2)
mat2=np.arange(6,10).reshape(2,2)
print("First matrix :\n",mat1)
print("Second Matrix :\n",mat2)
mult=np.dot(mat1,mat2)
addt=np.add(mat1,mat2)
print("Multiplied matrix: \n",mult)
print("Added matrix: \n",addt)

First matrix :
 [[1 2]
 [3 4]]
Second Matrix :
 [[6 7]
 [8 9]]
Multiplied matrix: 
 [[22 25]
 [50 57]]
Added matrix: 
 [[ 7  9]
 [11 13]]


13.Write a numpy program to find eigen values and eigen vectors of a given matrix.

In [17]:
import numpy as np
mat=np.arange(1,5).reshape(2,2)
print("Matrix is: \n",mat)
val,vec=np.linalg.eig(mat)
print("Eigen values: ",val)
print("Eigen vectors: \n",vec)

Matrix is: 
 [[1 2]
 [3 4]]
Eigen values:  [-0.37228132  5.37228132]
Eigen vectors: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


14.Write a program to find transpose, determinant and inverse of a matrix.

In [30]:
import numpy as np
mat=np.arange(1,5).reshape(2,2)
print("Matrix: \n",mat)
print("Transpose: \n",np.transpose(mat))
print("Determinant: ",int(np.linalg.det(mat)))
print("Inverse: \n",np.linalg.inv(mat))

Matrix: 
 [[1 2]
 [3 4]]
Transpose: 
 [[1 3]
 [2 4]]
Determinant:  -2
Inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
